import "./globals.css";
import Navbar from "./components/Navbar";
import { LoginProvider } from "./context/LoginContext";

export const metadata = {
  title: "STORYZER",
  description: "Generated by 우리팀",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <LoginProvider>
          <Navbar></Navbar> {/* 네브 헤더 */}
          {children} {/* 컨텐츠 */}
        </LoginProvider>
        <div id="portal"></div>
      </body>
    </html>
  );
}
